# Generated by Django 2.1.2 on 2019-06-26 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_p_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
