# Generated by Django 2.2 on 2019-06-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190626_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=50, verbose_name='제목')),
                ('b_content', models.CharField(max_length=50, verbose_name='제목')),
                ('b_isNotice', models.CharField(max_length=50, verbose_name='제목')),
            ],
        ),
        migrations.CreateModel(
            name='BoardFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_file', models.FileField(upload_to='', verbose_name='파일')),
                ('b_board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Board')),
            ],
        ),
    ]
