# Generated by Django 2.2 on 2019-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_board_boardfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.CharField(max_length=300, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_isNotice',
            field=models.BooleanField(default=False, verbose_name='제목'),
        ),
    ]
