# Generated by Django 2.2 on 2019-06-26 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0006_auto_20190626_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='b_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='board',
            name='b_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_content',
            field=models.CharField(max_length=300, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_isNotice',
            field=models.BooleanField(default=False, verbose_name='공지 여부'),
        ),
    ]
