# Generated by Django 2.2 on 2019-06-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190626_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='p_picture',
            field=models.ImageField(null=True, upload_to='', verbose_name='사진'),
        ),
    ]
