# Generated by Django 2.2 on 2019-06-29 16:25

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_profile_p_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardfiles',
            name='b_file',
            field=models.FileField(upload_to='Board', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p_picture',
            field=models.ImageField(null=True, upload_to=Main.models.save_pic_user, verbose_name='사진'),
        ),
    ]
