# Generated by Django 2.2 on 2019-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20190630_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=5)),
                ('g_email', models.CharField(max_length=30)),
                ('g_title', models.CharField(max_length=20)),
                ('g_content', models.CharField(max_length=50)),
                ('g_date', models.DateTimeField(auto_now_add=True)),
                ('g_ip', models.CharField(max_length=20)),
            ],
        ),
    ]
