# Generated by Django 2.2 on 2019-07-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_guestbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_rankcode', models.CharField(max_length=5)),
                ('r_images', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_user', models.CharField(max_length=50)),
                ('s_date', models.DateTimeField(null=True)),
                ('s_content', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='b_category',
            field=models.CharField(choices=[('정보', '정보'), ('기타', '기타')], default='정보', max_length=5, verbose_name='분류'),
        ),
        migrations.AddField(
            model_name='profile',
            name='p_rank',
            field=models.CharField(choices=[('재학생', '재학생'), ('졸업생', '졸업생'), ('실장', '실장')], default='재학생', max_length=5, verbose_name='신분'),
        ),
        migrations.AlterField(
            model_name='board',
            name='b_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
