# Generated by Django 2.2 on 2019-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20190701_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='s_finished_date',
            field=models.DateTimeField(null=True),
        ),
    ]
