# Generated by Django 2.1.2 on 2019-07-02 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_profile_p_rank_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='p_rank_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main.RankPicture', verbose_name='계급 사진'),
        ),
    ]
